spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: patientservice
          uri: http://patientservice:8081
          predicates:
            - Path=/api/patient/**
        - id: noteservice
          uri: http://noteservice:8082
          predicates:
            - Path=/api/note/**
        - id: riskservice
          uri: http://riskservice:8083
          predicates:
            - Path=/api/risk/**
server:
  port: 8080
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG